<?php
/**
 * This file is part of the Capsule package.
 *
 * (c) Alexander Polyanin 2006 <polyanin@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Date: 13.02.2017
 * Time: 20:43
 */

namespace App\Cms\Controller\Plugin;


use App\Cms\Controller\ReferenceController;
use App\Cms\Ui\ActionMenu\Callback;

class UserFiles extends ReferenceController
{
    protected $moduleClass = 'App\\Cms\\Plugin\\UserFiles\\File';

    protected function listItems(array $param = [])
    {
        $toolbar = $this->app->registry->actionMenu;
        parent::listItems(); // TODO: Change the autogenerated stub
        $toolbar->newMenuItem('Batch', new Callback('CapsuleCmsDataGrid.getInstance().batchAddFilesPlugin();'));
    }
}