<?php
/* vim: set expandtab tabstop=4 softtabstop=4 shiftwidth=4: */
// +---------------------------------------------------------------------------+
// | PHP version 5.4.7                                                         |
// +---------------------------------------------------------------------------+
// | Copyright (c) 2006-2014                                                   |
// +---------------------------------------------------------------------------+
// | 08.03.2014 3:32:18 YEKT 2014                                              |
// | Класс - type_description_here                                             |
// +---------------------------------------------------------------------------+
// | Author: Alexander Polyanin <polyanin@gmail.com>                           |
// +---------------------------------------------------------------------------+
//
// $Id$
/**
 * @package Capsule
 */

namespace App\Cms\Controller\Component\PhotoGallery;
use App\Cms\Controller\NestedItem;
use App\Cms\Ui\ActionMenu\Callback;
use Respect\Validation\Validator;


/**
 * Named.php
 *
 * @package Capsule
 * @author Alexander Polyanin <polyanin@gmail.com>
 */
class Photo extends NestedItem
{
    protected $moduleClass = '\\App\\Cms\\Component\\PhotoGallery\\Photo';

    protected function listItems(array $param = [])
    {
        parent::listItems(['row_class'=>'fat-row']); // TODO: Change the autogenerated stub
        $filter = $this->app->urlFilter;
        $toolbar = $this->app->registry->actionMenu;
        $container = $this->env->get($this->filterByContainerKey());
        if (Validator::digit()->validate($container)) {
            $toolbar->newMenuItem('Batch', new Callback('CapsuleCmsFileUploader.getInstance().done=function(){location.reload();};CapsuleCmsFileUploader.getInstance().setUrl("/ajax/uploadImage/Gallery/' . $container . '/").showWindow();'));
        }
    }
}